title: My WildCat Studios Portfolio
description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://Il2623639.github.io" # replace YOURUSERNAME with your GitHub username
theme:remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
